paths:
  /api/product/:
    get:
      summary: Obtener a todos los usuarios
      tags: 
        - Products
      responses:
        '200':
          description: Usuarios obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor al obtener los usuarios
    post:
      summary: Ingresar productos
      tags: 
        - Products
      responses:
        '200':
          description: Usuarios obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor al obtener los usuarios
          
  /api/product/{id}:
    get:
      summary: Obtener un solo usuario dado su id
      tags: 
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            $type: String
          description: Id del usuario a buscar
      responses:
        '200':
          description: Usuario obtenido satisfactoriamente
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor al obtener los usuarios
    put:
      summary: Modificar producto
      tags: 
        - Products
      responses:
        '200':
          description: Usuarios obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor al obtener los usuarios          
    delete:
      summary: Eliminar producto
      tags: 
        - Products
      responses:
        '200':
          description: Usuarios obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor al obtener los usuarios          
  /api/product/mockingProducts:
    post:
      summary: Obtener a todos los usuarios
      tags: 
        - Products
      responses:
        '200':
          description: Usuarios obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor al obtener los usuarios          